# Generated by Django 3.1.14 on 2023-12-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_auto_20231208_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
